# Apache configuration file.

<VirtualHost *:80>
    # ServerName bing-archive.salvino.me
    DocumentRoot /opt/bing-archive/www/
    <Directory "/">
        Options Indexes FollowSymlinks
        Require all granted
    </Directory>
</VirtualHost>
